// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

//在命令行执行:protoc --go_out=plugins=grpc:. grpc.proto
//gRPC 的流式，分为三种类型：服务器端流式 RPC,客户端流式 RPC,双向流式 RPC

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//--------------GetRow()---------------------------------
//GetRow,请求的参数.
type GetRowRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Pkey                 string   `protobuf:"bytes,2,opt,name=Pkey,proto3" json:"Pkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRowRequest) Reset()         { *m = GetRowRequest{} }
func (m *GetRowRequest) String() string { return proto.CompactTextString(m) }
func (*GetRowRequest) ProtoMessage()    {}
func (*GetRowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *GetRowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRowRequest.Unmarshal(m, b)
}
func (m *GetRowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRowRequest.Marshal(b, m, deterministic)
}
func (m *GetRowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRowRequest.Merge(m, src)
}
func (m *GetRowRequest) XXX_Size() int {
	return xxx_messageInfo_GetRowRequest.Size(m)
}
func (m *GetRowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRowRequest proto.InternalMessageInfo

func (m *GetRowRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *GetRowRequest) GetPkey() string {
	if m != nil {
		return m.Pkey
	}
	return ""
}

//GetRow,响应的结果.
type GetRowResponse struct {
	Result               map[string]string `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetRowResponse) Reset()         { *m = GetRowResponse{} }
func (m *GetRowResponse) String() string { return proto.CompactTextString(m) }
func (*GetRowResponse) ProtoMessage()    {}
func (*GetRowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *GetRowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRowResponse.Unmarshal(m, b)
}
func (m *GetRowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRowResponse.Marshal(b, m, deterministic)
}
func (m *GetRowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRowResponse.Merge(m, src)
}
func (m *GetRowResponse) XXX_Size() int {
	return xxx_messageInfo_GetRowResponse.Size(m)
}
func (m *GetRowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRowResponse proto.InternalMessageInfo

func (m *GetRowResponse) GetResult() map[string]string {
	if m != nil {
		return m.Result
	}
	return nil
}

//--------------GetColumn()---------------------------------
type GetColumnRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Pkey                 string   `protobuf:"bytes,2,opt,name=Pkey,proto3" json:"Pkey,omitempty"`
	Column               string   `protobuf:"bytes,3,opt,name=Column,proto3" json:"Column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetColumnRequest) Reset()         { *m = GetColumnRequest{} }
func (m *GetColumnRequest) String() string { return proto.CompactTextString(m) }
func (*GetColumnRequest) ProtoMessage()    {}
func (*GetColumnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *GetColumnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetColumnRequest.Unmarshal(m, b)
}
func (m *GetColumnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetColumnRequest.Marshal(b, m, deterministic)
}
func (m *GetColumnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetColumnRequest.Merge(m, src)
}
func (m *GetColumnRequest) XXX_Size() int {
	return xxx_messageInfo_GetColumnRequest.Size(m)
}
func (m *GetColumnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetColumnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetColumnRequest proto.InternalMessageInfo

func (m *GetColumnRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *GetColumnRequest) GetPkey() string {
	if m != nil {
		return m.Pkey
	}
	return ""
}

func (m *GetColumnRequest) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

type GetColumnResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetColumnResponse) Reset()         { *m = GetColumnResponse{} }
func (m *GetColumnResponse) String() string { return proto.CompactTextString(m) }
func (*GetColumnResponse) ProtoMessage()    {}
func (*GetColumnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *GetColumnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetColumnResponse.Unmarshal(m, b)
}
func (m *GetColumnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetColumnResponse.Marshal(b, m, deterministic)
}
func (m *GetColumnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetColumnResponse.Merge(m, src)
}
func (m *GetColumnResponse) XXX_Size() int {
	return xxx_messageInfo_GetColumnResponse.Size(m)
}
func (m *GetColumnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetColumnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetColumnResponse proto.InternalMessageInfo

func (m *GetColumnResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

//--------------DelRow()---------------------------------
type DelRowRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Pkey                 string   `protobuf:"bytes,2,opt,name=Pkey,proto3" json:"Pkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRowRequest) Reset()         { *m = DelRowRequest{} }
func (m *DelRowRequest) String() string { return proto.CompactTextString(m) }
func (*DelRowRequest) ProtoMessage()    {}
func (*DelRowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{4}
}

func (m *DelRowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRowRequest.Unmarshal(m, b)
}
func (m *DelRowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRowRequest.Marshal(b, m, deterministic)
}
func (m *DelRowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRowRequest.Merge(m, src)
}
func (m *DelRowRequest) XXX_Size() int {
	return xxx_messageInfo_DelRowRequest.Size(m)
}
func (m *DelRowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelRowRequest proto.InternalMessageInfo

func (m *DelRowRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *DelRowRequest) GetPkey() string {
	if m != nil {
		return m.Pkey
	}
	return ""
}

type DelRowResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRowResponse) Reset()         { *m = DelRowResponse{} }
func (m *DelRowResponse) String() string { return proto.CompactTextString(m) }
func (*DelRowResponse) ProtoMessage()    {}
func (*DelRowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{5}
}

func (m *DelRowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRowResponse.Unmarshal(m, b)
}
func (m *DelRowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRowResponse.Marshal(b, m, deterministic)
}
func (m *DelRowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRowResponse.Merge(m, src)
}
func (m *DelRowResponse) XXX_Size() int {
	return xxx_messageInfo_DelRowResponse.Size(m)
}
func (m *DelRowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelRowResponse proto.InternalMessageInfo

func (m *DelRowResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

//--------------GetWhere()---------------------------------
type GetWhereRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Where                string   `protobuf:"bytes,2,opt,name=Where,proto3" json:"Where,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWhereRequest) Reset()         { *m = GetWhereRequest{} }
func (m *GetWhereRequest) String() string { return proto.CompactTextString(m) }
func (*GetWhereRequest) ProtoMessage()    {}
func (*GetWhereRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{6}
}

func (m *GetWhereRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWhereRequest.Unmarshal(m, b)
}
func (m *GetWhereRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWhereRequest.Marshal(b, m, deterministic)
}
func (m *GetWhereRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWhereRequest.Merge(m, src)
}
func (m *GetWhereRequest) XXX_Size() int {
	return xxx_messageInfo_GetWhereRequest.Size(m)
}
func (m *GetWhereRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWhereRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWhereRequest proto.InternalMessageInfo

func (m *GetWhereRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *GetWhereRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

//服务器端流式 RPC
type GetWhereResponse struct {
	Result               *GetWhereStream `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetWhereResponse) Reset()         { *m = GetWhereResponse{} }
func (m *GetWhereResponse) String() string { return proto.CompactTextString(m) }
func (*GetWhereResponse) ProtoMessage()    {}
func (*GetWhereResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{7}
}

func (m *GetWhereResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWhereResponse.Unmarshal(m, b)
}
func (m *GetWhereResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWhereResponse.Marshal(b, m, deterministic)
}
func (m *GetWhereResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWhereResponse.Merge(m, src)
}
func (m *GetWhereResponse) XXX_Size() int {
	return xxx_messageInfo_GetWhereResponse.Size(m)
}
func (m *GetWhereResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWhereResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWhereResponse proto.InternalMessageInfo

func (m *GetWhereResponse) GetResult() *GetWhereStream {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetWhereStream struct {
	Result               map[string]string `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetWhereStream) Reset()         { *m = GetWhereStream{} }
func (m *GetWhereStream) String() string { return proto.CompactTextString(m) }
func (*GetWhereStream) ProtoMessage()    {}
func (*GetWhereStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{8}
}

func (m *GetWhereStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWhereStream.Unmarshal(m, b)
}
func (m *GetWhereStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWhereStream.Marshal(b, m, deterministic)
}
func (m *GetWhereStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWhereStream.Merge(m, src)
}
func (m *GetWhereStream) XXX_Size() int {
	return xxx_messageInfo_GetWhereStream.Size(m)
}
func (m *GetWhereStream) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWhereStream.DiscardUnknown(m)
}

var xxx_messageInfo_GetWhereStream proto.InternalMessageInfo

func (m *GetWhereStream) GetResult() map[string]string {
	if m != nil {
		return m.Result
	}
	return nil
}

//--------------UpdateColumn()---------------------------------
type UpdateColumnRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Pkey                 string   `protobuf:"bytes,2,opt,name=Pkey,proto3" json:"Pkey,omitempty"`
	Column               string   `protobuf:"bytes,3,opt,name=Column,proto3" json:"Column,omitempty"`
	ColumnValue          string   `protobuf:"bytes,4,opt,name=ColumnValue,proto3" json:"ColumnValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateColumnRequest) Reset()         { *m = UpdateColumnRequest{} }
func (m *UpdateColumnRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateColumnRequest) ProtoMessage()    {}
func (*UpdateColumnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{9}
}

func (m *UpdateColumnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateColumnRequest.Unmarshal(m, b)
}
func (m *UpdateColumnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateColumnRequest.Marshal(b, m, deterministic)
}
func (m *UpdateColumnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateColumnRequest.Merge(m, src)
}
func (m *UpdateColumnRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateColumnRequest.Size(m)
}
func (m *UpdateColumnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateColumnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateColumnRequest proto.InternalMessageInfo

func (m *UpdateColumnRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *UpdateColumnRequest) GetPkey() string {
	if m != nil {
		return m.Pkey
	}
	return ""
}

func (m *UpdateColumnRequest) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *UpdateColumnRequest) GetColumnValue() string {
	if m != nil {
		return m.ColumnValue
	}
	return ""
}

type UpdateColumnResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateColumnResponse) Reset()         { *m = UpdateColumnResponse{} }
func (m *UpdateColumnResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateColumnResponse) ProtoMessage()    {}
func (*UpdateColumnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{10}
}

func (m *UpdateColumnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateColumnResponse.Unmarshal(m, b)
}
func (m *UpdateColumnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateColumnResponse.Marshal(b, m, deterministic)
}
func (m *UpdateColumnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateColumnResponse.Merge(m, src)
}
func (m *UpdateColumnResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateColumnResponse.Size(m)
}
func (m *UpdateColumnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateColumnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateColumnResponse proto.InternalMessageInfo

func (m *UpdateColumnResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

//--------------UpdateColumns()---------------------------------
type UpdateColumnsRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Pkey                 string   `protobuf:"bytes,2,opt,name=Pkey,proto3" json:"Pkey,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=Where,proto3" json:"Where,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateColumnsRequest) Reset()         { *m = UpdateColumnsRequest{} }
func (m *UpdateColumnsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateColumnsRequest) ProtoMessage()    {}
func (*UpdateColumnsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{11}
}

func (m *UpdateColumnsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateColumnsRequest.Unmarshal(m, b)
}
func (m *UpdateColumnsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateColumnsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateColumnsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateColumnsRequest.Merge(m, src)
}
func (m *UpdateColumnsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateColumnsRequest.Size(m)
}
func (m *UpdateColumnsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateColumnsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateColumnsRequest proto.InternalMessageInfo

func (m *UpdateColumnsRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *UpdateColumnsRequest) GetPkey() string {
	if m != nil {
		return m.Pkey
	}
	return ""
}

func (m *UpdateColumnsRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

type UpdateColumnsResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateColumnsResponse) Reset()         { *m = UpdateColumnsResponse{} }
func (m *UpdateColumnsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateColumnsResponse) ProtoMessage()    {}
func (*UpdateColumnsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{12}
}

func (m *UpdateColumnsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateColumnsResponse.Unmarshal(m, b)
}
func (m *UpdateColumnsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateColumnsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateColumnsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateColumnsResponse.Merge(m, src)
}
func (m *UpdateColumnsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateColumnsResponse.Size(m)
}
func (m *UpdateColumnsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateColumnsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateColumnsResponse proto.InternalMessageInfo

func (m *UpdateColumnsResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

//--------------InsertRow()---------------------------------
type InsertRowRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Condition            string   `protobuf:"bytes,2,opt,name=Condition,proto3" json:"Condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertRowRequest) Reset()         { *m = InsertRowRequest{} }
func (m *InsertRowRequest) String() string { return proto.CompactTextString(m) }
func (*InsertRowRequest) ProtoMessage()    {}
func (*InsertRowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{13}
}

func (m *InsertRowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRowRequest.Unmarshal(m, b)
}
func (m *InsertRowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRowRequest.Marshal(b, m, deterministic)
}
func (m *InsertRowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRowRequest.Merge(m, src)
}
func (m *InsertRowRequest) XXX_Size() int {
	return xxx_messageInfo_InsertRowRequest.Size(m)
}
func (m *InsertRowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRowRequest proto.InternalMessageInfo

func (m *InsertRowRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *InsertRowRequest) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type InsertRowResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertRowResponse) Reset()         { *m = InsertRowResponse{} }
func (m *InsertRowResponse) String() string { return proto.CompactTextString(m) }
func (*InsertRowResponse) ProtoMessage()    {}
func (*InsertRowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{14}
}

func (m *InsertRowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRowResponse.Unmarshal(m, b)
}
func (m *InsertRowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRowResponse.Marshal(b, m, deterministic)
}
func (m *InsertRowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRowResponse.Merge(m, src)
}
func (m *InsertRowResponse) XXX_Size() int {
	return xxx_messageInfo_InsertRowResponse.Size(m)
}
func (m *InsertRowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRowResponse proto.InternalMessageInfo

func (m *InsertRowResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

//--------------GetRowBetween()---------------------------------
type GetRowBetweenRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End                  int64    `protobuf:"varint,3,opt,name=End,proto3" json:"End,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRowBetweenRequest) Reset()         { *m = GetRowBetweenRequest{} }
func (m *GetRowBetweenRequest) String() string { return proto.CompactTextString(m) }
func (*GetRowBetweenRequest) ProtoMessage()    {}
func (*GetRowBetweenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{15}
}

func (m *GetRowBetweenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRowBetweenRequest.Unmarshal(m, b)
}
func (m *GetRowBetweenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRowBetweenRequest.Marshal(b, m, deterministic)
}
func (m *GetRowBetweenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRowBetweenRequest.Merge(m, src)
}
func (m *GetRowBetweenRequest) XXX_Size() int {
	return xxx_messageInfo_GetRowBetweenRequest.Size(m)
}
func (m *GetRowBetweenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRowBetweenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRowBetweenRequest proto.InternalMessageInfo

func (m *GetRowBetweenRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *GetRowBetweenRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetRowBetweenRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

//服务器端流式 RPC
type GetRowBetweenResponse struct {
	Result               *GetRowBetweentream `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetRowBetweenResponse) Reset()         { *m = GetRowBetweenResponse{} }
func (m *GetRowBetweenResponse) String() string { return proto.CompactTextString(m) }
func (*GetRowBetweenResponse) ProtoMessage()    {}
func (*GetRowBetweenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{16}
}

func (m *GetRowBetweenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRowBetweenResponse.Unmarshal(m, b)
}
func (m *GetRowBetweenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRowBetweenResponse.Marshal(b, m, deterministic)
}
func (m *GetRowBetweenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRowBetweenResponse.Merge(m, src)
}
func (m *GetRowBetweenResponse) XXX_Size() int {
	return xxx_messageInfo_GetRowBetweenResponse.Size(m)
}
func (m *GetRowBetweenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRowBetweenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRowBetweenResponse proto.InternalMessageInfo

func (m *GetRowBetweenResponse) GetResult() *GetRowBetweentream {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetRowBetweentream struct {
	Result               map[string]string `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetRowBetweentream) Reset()         { *m = GetRowBetweentream{} }
func (m *GetRowBetweentream) String() string { return proto.CompactTextString(m) }
func (*GetRowBetweentream) ProtoMessage()    {}
func (*GetRowBetweentream) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{17}
}

func (m *GetRowBetweentream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRowBetweentream.Unmarshal(m, b)
}
func (m *GetRowBetweentream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRowBetweentream.Marshal(b, m, deterministic)
}
func (m *GetRowBetweentream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRowBetweentream.Merge(m, src)
}
func (m *GetRowBetweentream) XXX_Size() int {
	return xxx_messageInfo_GetRowBetweentream.Size(m)
}
func (m *GetRowBetweentream) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRowBetweentream.DiscardUnknown(m)
}

var xxx_messageInfo_GetRowBetweentream proto.InternalMessageInfo

func (m *GetRowBetweentream) GetResult() map[string]string {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRowRequest)(nil), "pb.GetRowRequest")
	proto.RegisterType((*GetRowResponse)(nil), "pb.GetRowResponse")
	proto.RegisterMapType((map[string]string)(nil), "pb.GetRowResponse.ResultEntry")
	proto.RegisterType((*GetColumnRequest)(nil), "pb.GetColumnRequest")
	proto.RegisterType((*GetColumnResponse)(nil), "pb.GetColumnResponse")
	proto.RegisterType((*DelRowRequest)(nil), "pb.DelRowRequest")
	proto.RegisterType((*DelRowResponse)(nil), "pb.DelRowResponse")
	proto.RegisterType((*GetWhereRequest)(nil), "pb.GetWhereRequest")
	proto.RegisterType((*GetWhereResponse)(nil), "pb.GetWhereResponse")
	proto.RegisterType((*GetWhereStream)(nil), "pb.GetWhereStream")
	proto.RegisterMapType((map[string]string)(nil), "pb.GetWhereStream.ResultEntry")
	proto.RegisterType((*UpdateColumnRequest)(nil), "pb.UpdateColumnRequest")
	proto.RegisterType((*UpdateColumnResponse)(nil), "pb.UpdateColumnResponse")
	proto.RegisterType((*UpdateColumnsRequest)(nil), "pb.UpdateColumnsRequest")
	proto.RegisterType((*UpdateColumnsResponse)(nil), "pb.UpdateColumnsResponse")
	proto.RegisterType((*InsertRowRequest)(nil), "pb.InsertRowRequest")
	proto.RegisterType((*InsertRowResponse)(nil), "pb.InsertRowResponse")
	proto.RegisterType((*GetRowBetweenRequest)(nil), "pb.GetRowBetweenRequest")
	proto.RegisterType((*GetRowBetweenResponse)(nil), "pb.GetRowBetweenResponse")
	proto.RegisterType((*GetRowBetweentream)(nil), "pb.GetRowBetweentream")
	proto.RegisterMapType((map[string]string)(nil), "pb.GetRowBetweentream.ResultEntry")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0xe3, 0x36, 0xfa, 0x65, 0xf2, 0x6b, 0x49, 0xa7, 0x4e, 0x08, 0x51, 0x85, 0x22, 0x9f,
	0x22, 0x90, 0x9c, 0x2a, 0x48, 0x50, 0x7a, 0x40, 0x6a, 0x9b, 0x60, 0x71, 0xa9, 0x90, 0xcb, 0x9f,
	0x4b, 0x85, 0xe4, 0x24, 0x23, 0x5a, 0xe1, 0xd8, 0xc6, 0xde, 0x50, 0xf5, 0x88, 0x38, 0xf2, 0x59,
	0xf9, 0x0e, 0xc8, 0xbb, 0x6b, 0x67, 0xfd, 0x07, 0x25, 0x2a, 0xe5, 0xb6, 0x3b, 0xfb, 0x3c, 0x6f,
	0x76, 0xf6, 0xcd, 0x33, 0xc0, 0xe7, 0x28, 0x9c, 0x59, 0x61, 0x14, 0xb0, 0x00, 0x6b, 0xe1, 0xd4,
	0x3c, 0x81, 0x1d, 0x9b, 0x98, 0x13, 0xdc, 0x38, 0xf4, 0x75, 0x49, 0x31, 0xc3, 0x03, 0x68, 0xbc,
	0x73, 0xa7, 0x1e, 0x9d, 0xbb, 0x0b, 0xea, 0x6a, 0x7d, 0x6d, 0xd0, 0x70, 0x56, 0x01, 0x44, 0xd8,
	0x7a, 0xfb, 0x85, 0x6e, 0xbb, 0x35, 0x7e, 0xc0, 0xd7, 0xe6, 0x0f, 0x0d, 0x76, 0xd3, 0x1c, 0x71,
	0x18, 0xf8, 0x31, 0xe1, 0x73, 0xa8, 0x3b, 0x14, 0x2f, 0x3d, 0xd6, 0xd5, 0xfa, 0xfa, 0xa0, 0x39,
	0x7a, 0x6c, 0x85, 0x53, 0x2b, 0x8f, 0xb1, 0x04, 0x60, 0xe2, 0xb3, 0xe8, 0xd6, 0x91, 0xe8, 0xde,
	0x4b, 0x68, 0x2a, 0x61, 0x6c, 0x81, 0x9e, 0x90, 0x89, 0x2a, 0x92, 0x25, 0x1a, 0xb0, 0xfd, 0xcd,
	0xf5, 0x96, 0x24, 0x0b, 0x10, 0x9b, 0xe3, 0xda, 0x91, 0x66, 0x5e, 0x42, 0xcb, 0x26, 0x76, 0x16,
	0x78, 0xcb, 0x85, 0x7f, 0xe7, 0xbb, 0x60, 0x07, 0xea, 0x22, 0x45, 0x57, 0xe7, 0x51, 0xb9, 0x33,
	0x9f, 0xc2, 0x9e, 0x92, 0x5d, 0xde, 0xb2, 0xa3, 0xdc, 0x92, 0x83, 0xc5, 0x2e, 0xe9, 0xe9, 0x98,
	0xbc, 0xbf, 0xea, 0xe9, 0x00, 0x76, 0xd3, 0x14, 0x95, 0x64, 0x7a, 0x46, 0x36, 0x81, 0x07, 0x36,
	0xb1, 0x8f, 0x57, 0x14, 0xd1, 0x66, 0x74, 0x06, 0x6c, 0x73, 0x74, 0xda, 0x42, 0xbe, 0x31, 0x5f,
	0xf1, 0xf6, 0xc9, 0x34, 0x92, 0xf2, 0x49, 0x8e, 0xb2, 0x39, 0x42, 0xf9, 0x8a, 0x1c, 0x75, 0xc1,
	0x22, 0x72, 0x17, 0x59, 0x19, 0x52, 0x04, 0xca, 0xd1, 0x1f, 0x45, 0xa0, 0x60, 0xee, 0x5b, 0x04,
	0xdf, 0x35, 0xd8, 0x7f, 0x1f, 0xce, 0x5d, 0x46, 0xff, 0x48, 0x08, 0xd8, 0x87, 0xa6, 0x58, 0x7d,
	0xe0, 0x15, 0x6c, 0xf1, 0x43, 0x35, 0x64, 0x5a, 0x60, 0xe4, 0x4b, 0x58, 0xf3, 0x80, 0x9f, 0xf2,
	0xf8, 0xf8, 0xee, 0x35, 0x67, 0x2f, 0xab, 0xab, 0x2f, 0x3b, 0x84, 0x76, 0x21, 0xff, 0x9a, 0x82,
	0xce, 0xa1, 0xf5, 0xc6, 0x8f, 0x29, 0xda, 0xdc, 0x15, 0x0e, 0xa0, 0x71, 0x16, 0xf8, 0xf3, 0x6b,
	0x76, 0x1d, 0xf8, 0xb2, 0xa2, 0x55, 0x20, 0x99, 0x1d, 0x25, 0xdf, 0x1a, 0xf2, 0x4b, 0x30, 0x84,
	0x4f, 0x9c, 0x12, 0xbb, 0x21, 0xf2, 0x37, 0xd6, 0xf4, 0x05, 0x73, 0x23, 0xc6, 0xc9, 0x75, 0x47,
	0x6c, 0x12, 0xe5, 0x4c, 0xfc, 0x39, 0xef, 0x86, 0xee, 0x24, 0x4b, 0xd3, 0x86, 0x76, 0x21, 0xbb,
	0x2c, 0xc7, 0x2a, 0x48, 0xbd, 0xb3, 0x32, 0x2c, 0x09, 0xcd, 0xcb, 0xfd, 0xa7, 0x06, 0x58, 0x3e,
	0xc6, 0xe3, 0x82, 0xe4, 0xcd, 0xea, 0x34, 0xf7, 0x2c, 0xfb, 0xd1, 0x2f, 0x1d, 0x9a, 0x76, 0x14,
	0xce, 0xc6, 0xa7, 0x33, 0x77, 0x76, 0x45, 0x38, 0x84, 0xba, 0x20, 0xc5, 0x3d, 0xd5, 0x78, 0x79,
	0x27, 0x7b, 0x58, 0xf6, 0x62, 0x3c, 0x82, 0x46, 0x66, 0x6f, 0x68, 0x48, 0x40, 0x6e, 0x84, 0x7a,
	0xed, 0x42, 0x54, 0x7e, 0x39, 0x84, 0xba, 0x30, 0x2a, 0x41, 0x95, 0xf3, 0x3d, 0x41, 0x55, 0xf0,
	0xb1, 0x17, 0xf0, 0x5f, 0xea, 0x01, 0xb8, 0xaf, 0x3a, 0x42, 0xfa, 0x91, 0x91, 0x0f, 0x8a, 0xcf,
	0x0e, 0x35, 0x3c, 0x81, 0xff, 0x55, 0x1d, 0xe3, 0xc3, 0x04, 0x57, 0x31, 0xec, 0xbd, 0x6e, 0xf9,
	0x40, 0x72, 0x8f, 0x61, 0x27, 0x37, 0x0a, 0x58, 0x82, 0xa6, 0xd3, 0xd7, 0x7b, 0x54, 0x71, 0xb2,
	0x6a, 0x56, 0xa6, 0x67, 0xd1, 0xac, 0xe2, 0xb8, 0x88, 0x66, 0x95, 0x45, 0xff, 0x3a, 0xfd, 0xd9,
	0x4a, 0x31, 0x08, 0xfe, 0x2a, 0xbd, 0x0b, 0xfe, 0x4a, 0xad, 0x1e, 0x6a, 0xd3, 0x3a, 0xff, 0x7f,
	0x3f, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x75, 0xc2, 0x3d, 0xcd, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrpcDBcacheClient is the client API for GrpcDBcache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcDBcacheClient interface {
	GetRow(ctx context.Context, in *GetRowRequest, opts ...grpc.CallOption) (*GetRowResponse, error)
	GetColumn(ctx context.Context, in *GetColumnRequest, opts ...grpc.CallOption) (*GetColumnResponse, error)
	DelRow(ctx context.Context, in *DelRowRequest, opts ...grpc.CallOption) (*DelRowResponse, error)
	//服务器端流式 RPC,注意关键字 stream，声明其为一个流方法。
	GetWhere(ctx context.Context, in *GetWhereRequest, opts ...grpc.CallOption) (GrpcDBcache_GetWhereClient, error)
	UpdateColumn(ctx context.Context, in *UpdateColumnRequest, opts ...grpc.CallOption) (*UpdateColumnResponse, error)
	UpdateColumns(ctx context.Context, in *UpdateColumnsRequest, opts ...grpc.CallOption) (*UpdateColumnsResponse, error)
	InsertRow(ctx context.Context, in *InsertRowRequest, opts ...grpc.CallOption) (*InsertRowResponse, error)
	//服务器端流式 RPC,注意关键字 stream，声明其为一个流方法。
	GetRowBetween(ctx context.Context, in *GetRowBetweenRequest, opts ...grpc.CallOption) (GrpcDBcache_GetRowBetweenClient, error)
}

type grpcDBcacheClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcDBcacheClient(cc grpc.ClientConnInterface) GrpcDBcacheClient {
	return &grpcDBcacheClient{cc}
}

func (c *grpcDBcacheClient) GetRow(ctx context.Context, in *GetRowRequest, opts ...grpc.CallOption) (*GetRowResponse, error) {
	out := new(GetRowResponse)
	err := c.cc.Invoke(ctx, "/pb.GrpcDBcache/GetRow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDBcacheClient) GetColumn(ctx context.Context, in *GetColumnRequest, opts ...grpc.CallOption) (*GetColumnResponse, error) {
	out := new(GetColumnResponse)
	err := c.cc.Invoke(ctx, "/pb.GrpcDBcache/GetColumn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDBcacheClient) DelRow(ctx context.Context, in *DelRowRequest, opts ...grpc.CallOption) (*DelRowResponse, error) {
	out := new(DelRowResponse)
	err := c.cc.Invoke(ctx, "/pb.GrpcDBcache/DelRow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDBcacheClient) GetWhere(ctx context.Context, in *GetWhereRequest, opts ...grpc.CallOption) (GrpcDBcache_GetWhereClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GrpcDBcache_serviceDesc.Streams[0], "/pb.GrpcDBcache/GetWhere", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcDBcacheGetWhereClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GrpcDBcache_GetWhereClient interface {
	Recv() (*GetWhereResponse, error)
	grpc.ClientStream
}

type grpcDBcacheGetWhereClient struct {
	grpc.ClientStream
}

func (x *grpcDBcacheGetWhereClient) Recv() (*GetWhereResponse, error) {
	m := new(GetWhereResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcDBcacheClient) UpdateColumn(ctx context.Context, in *UpdateColumnRequest, opts ...grpc.CallOption) (*UpdateColumnResponse, error) {
	out := new(UpdateColumnResponse)
	err := c.cc.Invoke(ctx, "/pb.GrpcDBcache/UpdateColumn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDBcacheClient) UpdateColumns(ctx context.Context, in *UpdateColumnsRequest, opts ...grpc.CallOption) (*UpdateColumnsResponse, error) {
	out := new(UpdateColumnsResponse)
	err := c.cc.Invoke(ctx, "/pb.GrpcDBcache/UpdateColumns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDBcacheClient) InsertRow(ctx context.Context, in *InsertRowRequest, opts ...grpc.CallOption) (*InsertRowResponse, error) {
	out := new(InsertRowResponse)
	err := c.cc.Invoke(ctx, "/pb.GrpcDBcache/InsertRow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDBcacheClient) GetRowBetween(ctx context.Context, in *GetRowBetweenRequest, opts ...grpc.CallOption) (GrpcDBcache_GetRowBetweenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GrpcDBcache_serviceDesc.Streams[1], "/pb.GrpcDBcache/GetRowBetween", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcDBcacheGetRowBetweenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GrpcDBcache_GetRowBetweenClient interface {
	Recv() (*GetRowBetweenResponse, error)
	grpc.ClientStream
}

type grpcDBcacheGetRowBetweenClient struct {
	grpc.ClientStream
}

func (x *grpcDBcacheGetRowBetweenClient) Recv() (*GetRowBetweenResponse, error) {
	m := new(GetRowBetweenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcDBcacheServer is the server API for GrpcDBcache service.
type GrpcDBcacheServer interface {
	GetRow(context.Context, *GetRowRequest) (*GetRowResponse, error)
	GetColumn(context.Context, *GetColumnRequest) (*GetColumnResponse, error)
	DelRow(context.Context, *DelRowRequest) (*DelRowResponse, error)
	//服务器端流式 RPC,注意关键字 stream，声明其为一个流方法。
	GetWhere(*GetWhereRequest, GrpcDBcache_GetWhereServer) error
	UpdateColumn(context.Context, *UpdateColumnRequest) (*UpdateColumnResponse, error)
	UpdateColumns(context.Context, *UpdateColumnsRequest) (*UpdateColumnsResponse, error)
	InsertRow(context.Context, *InsertRowRequest) (*InsertRowResponse, error)
	//服务器端流式 RPC,注意关键字 stream，声明其为一个流方法。
	GetRowBetween(*GetRowBetweenRequest, GrpcDBcache_GetRowBetweenServer) error
}

// UnimplementedGrpcDBcacheServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcDBcacheServer struct {
}

func (*UnimplementedGrpcDBcacheServer) GetRow(ctx context.Context, req *GetRowRequest) (*GetRowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRow not implemented")
}
func (*UnimplementedGrpcDBcacheServer) GetColumn(ctx context.Context, req *GetColumnRequest) (*GetColumnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetColumn not implemented")
}
func (*UnimplementedGrpcDBcacheServer) DelRow(ctx context.Context, req *DelRowRequest) (*DelRowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelRow not implemented")
}
func (*UnimplementedGrpcDBcacheServer) GetWhere(req *GetWhereRequest, srv GrpcDBcache_GetWhereServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWhere not implemented")
}
func (*UnimplementedGrpcDBcacheServer) UpdateColumn(ctx context.Context, req *UpdateColumnRequest) (*UpdateColumnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateColumn not implemented")
}
func (*UnimplementedGrpcDBcacheServer) UpdateColumns(ctx context.Context, req *UpdateColumnsRequest) (*UpdateColumnsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateColumns not implemented")
}
func (*UnimplementedGrpcDBcacheServer) InsertRow(ctx context.Context, req *InsertRowRequest) (*InsertRowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertRow not implemented")
}
func (*UnimplementedGrpcDBcacheServer) GetRowBetween(req *GetRowBetweenRequest, srv GrpcDBcache_GetRowBetweenServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRowBetween not implemented")
}

func RegisterGrpcDBcacheServer(s *grpc.Server, srv GrpcDBcacheServer) {
	s.RegisterService(&_GrpcDBcache_serviceDesc, srv)
}

func _GrpcDBcache_GetRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDBcacheServer).GetRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GrpcDBcache/GetRow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDBcacheServer).GetRow(ctx, req.(*GetRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDBcache_GetColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDBcacheServer).GetColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GrpcDBcache/GetColumn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDBcacheServer).GetColumn(ctx, req.(*GetColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDBcache_DelRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDBcacheServer).DelRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GrpcDBcache/DelRow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDBcacheServer).DelRow(ctx, req.(*DelRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDBcache_GetWhere_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWhereRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcDBcacheServer).GetWhere(m, &grpcDBcacheGetWhereServer{stream})
}

type GrpcDBcache_GetWhereServer interface {
	Send(*GetWhereResponse) error
	grpc.ServerStream
}

type grpcDBcacheGetWhereServer struct {
	grpc.ServerStream
}

func (x *grpcDBcacheGetWhereServer) Send(m *GetWhereResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GrpcDBcache_UpdateColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDBcacheServer).UpdateColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GrpcDBcache/UpdateColumn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDBcacheServer).UpdateColumn(ctx, req.(*UpdateColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDBcache_UpdateColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateColumnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDBcacheServer).UpdateColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GrpcDBcache/UpdateColumns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDBcacheServer).UpdateColumns(ctx, req.(*UpdateColumnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDBcache_InsertRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDBcacheServer).InsertRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GrpcDBcache/InsertRow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDBcacheServer).InsertRow(ctx, req.(*InsertRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDBcache_GetRowBetween_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRowBetweenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcDBcacheServer).GetRowBetween(m, &grpcDBcacheGetRowBetweenServer{stream})
}

type GrpcDBcache_GetRowBetweenServer interface {
	Send(*GetRowBetweenResponse) error
	grpc.ServerStream
}

type grpcDBcacheGetRowBetweenServer struct {
	grpc.ServerStream
}

func (x *grpcDBcacheGetRowBetweenServer) Send(m *GetRowBetweenResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GrpcDBcache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GrpcDBcache",
	HandlerType: (*GrpcDBcacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRow",
			Handler:    _GrpcDBcache_GetRow_Handler,
		},
		{
			MethodName: "GetColumn",
			Handler:    _GrpcDBcache_GetColumn_Handler,
		},
		{
			MethodName: "DelRow",
			Handler:    _GrpcDBcache_DelRow_Handler,
		},
		{
			MethodName: "UpdateColumn",
			Handler:    _GrpcDBcache_UpdateColumn_Handler,
		},
		{
			MethodName: "UpdateColumns",
			Handler:    _GrpcDBcache_UpdateColumns_Handler,
		},
		{
			MethodName: "InsertRow",
			Handler:    _GrpcDBcache_InsertRow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWhere",
			Handler:       _GrpcDBcache_GetWhere_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetRowBetween",
			Handler:       _GrpcDBcache_GetRowBetween_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
